#!/bin/bash
############################################################################
# TITLE       : Repo Tools
# PROJECT     : Spacewalk
# ENGINEER    : waveclaw
# PROGRAM     : mount_repos
# FILE        : iso2repo 
# CREATED     : 10-JUN-2013 waveclaw
# DESCRIPTION : Bash Shell script to mount ISO files
# ASSUMPTIONS : Familiarity with bash 2.0
############################################################################
#                          RELEASE LISCENSE              
#
#       This file is available under copyright 2012. 
#       For internal use only, keep out of young children. 
#                                                                        
#       Other Copyrights to their respective owners.                           
#                                                                        
#  Current version : 0.1
#  Latest version  : 0.1
#  Bugs, Comments  : waveclaw@waveclaw.net
############################################################################
PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/sbin
OLDROOT=/var/www/html/pub/ISOs

if [ ! -x `which createrepo` ]
then
  echo 'No createrepo in path'
  exit 1
fi

usage() {
echo "Usage: `basename $0`"
cat <<EOU
 -l path    Location of the ISOs [default $OLDROOT]
 -h         This help text
EOU
}

while [ 0 -lt $# ]
do
case "$1" in 
 -h) 
   usage
   exit 0
   ;;
 -l) 
  shift
  ROOT="$1";
  shift
  ;;
 *) 
  echo "Unkown option $1"
  echo
  usage
  exit 1
  ;;
esac
done

if [ " $ROOT" == " " ]
then
ROOT=$OLDROOT
fi

if [ \! -d "$ROOT" ] 
then
 echo "${ROOT} not a directory!"
 echo
 usage
 exit 1
fi 

rm -rf /tmp/cr_cache.$$ 
mkdir -p /tmp/cr_cache.$$ 

for DISK in $ROOT/ISOs/*
do 
SRC=`basename ${DISK%.iso}`
MNT=$ROOT/repo/$SRC
REPO=$ROOT/yum/$SRC
rm -rf $REPO 
mkdir -p $REPO 
pushd $REPO 
find $MNT -type f -name '*.rpm' -exec ln -sf '{}' . \; && echo "Create a yum repo in $REPO" && createrepo -d -c /tmp/cr_cache.$$ $REPO
find $MNT -type f -name '*.deb' -exec ln -sf '{}' . \; && echo "Create a Debian Pool in $REPO"
popd 
done

rm -rf /tmp/cr_cache.$$ 
